#!/bin/sh
# rebase to provided branch
branch=$1 
if [ -z "$branch" ]
then
      branch="develop"
fi
git add .
# check if there are any changes in the current branch and save to varaible
changes=$(git status --porcelain)
# if there are changes stash them
if [ -n "$changes" ]
then
      git stash
fi
git checkout $branch  
git pull origin HEAD
git switch -
git rebase $branch
# if there were changes pop them
if [ -n "$changes" ]
then
      git stash pop
fi


