#!/bin/sh
# Shows diff between remote branch and local

git fetch
remoteBranch=$(git symbolic-ref --short -q HEAD)

if [ ! -z "$1" ]
then
  remoteBranch=$1
fi
echo "Showing diff between $remoteBranch origin/$remoteBranch"
git diff $remoteBranch origin/$remoteBranch